-- MySQL Script generated by MySQL Workbench
-- Sat Apr 18 14:14:21 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema world
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `iso_code` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`province` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_province_country_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_province_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_province_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_province`
    FOREIGN KEY (`province_id`)
    REFERENCES `mydb`.`province` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `is_headquarter` TINYINT(1) NULL,
  `email` VARCHAR(255) NULL,
  `phone_number` VARCHAR(255) NULL,
  `address` TEXT NULL,
  `city_id` INT NOT NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_branch_city_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_branch_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `national_code` VARCHAR(15) NOT NULL,
  `phone_number` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `branch_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `acount_status` TINYINT(1) NULL,
  `created_at` TIMESTAMP NULL,
  `me_zone` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `national_code_UNIQUE` (`national_code` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_employee_branch_idx` (`branch_id` ASC) VISIBLE,
  INDEX `fk_employee_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `national_code` VARCHAR(15) NOT NULL,
  `phone_number` VARCHAR(15) NULL,
  `address` TEXT NULL,
  `registered_by` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `national_code_UNIQUE` (`national_code` ASC) VISIBLE,
  INDEX `fk_customer_employee_idx` (`registered_by` ASC) VISIBLE,
  CONSTRAINT `fk_customer_employee`
    FOREIGN KEY (`registered_by`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`audit_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`audit_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `action_type` VARCHAR(50) NULL,
  `table_affected` VARCHAR(50) NULL,
  `record_id` INT NULL,
  `old_value` TEXT NULL,
  `new_value` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_audit_log_employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_audit_log_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `interest_rate` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_number` VARCHAR(16) NOT NULL,
  `customer_id` INT NOT NULL,
  `account_type_id` INT NOT NULL,
  `balance` DECIMAL(15,2) NOT NULL,
  `openend_by` INT NOT NULL,
  `opening_date` DATE NULL,
  `status` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_number_UNIQUE` (`account_number` ASC) VISIBLE,
  INDEX `fk_account_customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_account_ttype_idx` (`account_type_id` ASC) VISIBLE,
  INDEX `fk_account_employee_idx` (`openend_by` ASC) VISIBLE,
  CONSTRAINT `fk_account_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_type`
    FOREIGN KEY (`account_type_id`)
    REFERENCES `mydb`.`account_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_employee`
    FOREIGN KEY (`openend_by`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `card_number` VARCHAR(16) NOT NULL,
  `expiry_date` DATE NULL,
  `first_pin_character` VARCHAR(255) NULL,
  `second_pin_character` VARCHAR(255) NULL,
  `status` VARCHAR(10) NULL,
  `issued_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `card_number_UNIQUE` (`card_number` ASC) VISIBLE,
  INDEX `fk_card_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_card_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `from_account_id` INT NOT NULL,
  `to_account_id` INT NOT NULL,
  `account` DECIMAL(15,2) NOT NULL,
  `transaction_type` VARCHAR(20) NULL,
  `discription` VARCHAR(255) NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `status` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_from_account_idx` (`from_account_id` ASC) VISIBLE,
  INDEX `fk_transaction_to_account_idx` (`to_account_id` ASC) VISIBLE,
  INDEX `fk_transaction_employee_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_from_account`
    FOREIGN KEY (`from_account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_to_account`
    FOREIGN KEY (`to_account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_employee`
    FOREIGN KEY (`created_by`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `status` VARCHAR(10) NULL,
  `last_login_timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_customer_login_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`loan_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loan_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `max_amount` DECIMAL(15,2) NULL,
  `annual_interest_rate` DECIMAL(5,2) NULL,
  `max_installments` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`loan_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loan_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `loan_type_id` INT NOT NULL,
  `amount` DECIMAL(15,2) NULL,
  `requested_at` TIMESTAMP NULL,
  `status` VARCHAR(20) NULL,
  `approved_by` INT NULL,
  `approved_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_loan_request_customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_loan_request_type_idx` (`loan_type_id` ASC) VISIBLE,
  INDEX `fk_loan_request_employee_idx` (`approved_by` ASC) VISIBLE,
  CONSTRAINT `fk_loan_request_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loan_request_type`
    FOREIGN KEY (`loan_type_id`)
    REFERENCES `mydb`.`loan_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loan_request_employee`
    FOREIGN KEY (`approved_by`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`installment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`installment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loan_request_id` INT NOT NULL,
  `paid_amount` DECIMAL(15,2) NULL,
  `status` VARCHAR(10) NULL,
  `paid_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_installment_loan_request_idx` (`loan_request_id` ASC) VISIBLE,
  CONSTRAINT `fk_installment_loan_request`
    FOREIGN KEY (`loan_request_id`)
    REFERENCES `mydb`.`loan_request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_by` INT NOT NULL,
  `assigned_to` INT NULL,
  `subject` VARCHAR(20) NULL,
  `message` TEXT NULL,
  `status` VARCHAR(10) NULL,
  `created_at` TIMESTAMP NULL,
  `recieved_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_customer_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_ticket_employee_idx` (`assigned_to` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_customer`
    FOREIGN KEY (`created_by`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_employee`
    FOREIGN KEY (`assigned_to`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
